---
version: '2'
services:
  mysql:
    image: mysql:5.6
    hostname: some-mysql
    container_name: some-mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management
    hostname: some-rabbit
    container_name: some-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  zookeeper:
    image: zookeeper
    hostname: some-zookeeper
    container_name: some-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service
    hostname: cdc-service
    container_name: cdc-service
    depends_on:
      - zookeeper
      - rabbitmq
      - mysql
    environment:
      logging_level_root: info
      logging_level_java_sql: debug
      logging_level_org_springframework_jdbc: info
      eventuate_cdc_type: EventuatePolling
      eventuatelocal_zookeeper_connection_string: some-zookeeper:2181
      spring_profiles_active: RabbitMQ
      rabbitmq_url: some-rabbit
      eventuate_rabbitmq_partition_count: 4
      eventuate_cdc_reader_bankregistrationreader_type: polling
      eventuate_cdc_reader_bankregistrationreader_dataSourceUrl: jdbc:mysql://some-mysql/bank_registration?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
      eventuate_cdc_reader_bankregistrationreader_dataSourceUserName: root
      eventuate_cdc_reader_bankregistrationreader_dataSourcePassword: password
      eventuate_cdc_reader_bankregistrationreader_dataSourceDriverClassName: com.mysql.jdbc.Driver
      eventuate_cdc_reader_bankregistrationreader_leadershipLockPath: /eventuatelocal/cdc/bank_registration/leader/1
      eventuate_cdc_pipeline_bankregistrationpipeline_type: eventuate-tram
      eventuate_cdc_pipeline_bankregistrationpipeline_eventuateDatabaseSchema: bank_registration
      eventuate_cdc_pipeline_bankregistrationpipeline_sourceTableName: message
      eventuate_cdc_pipeline_bankregistrationpipeline_reader: bankregistrationreader
  broker:
    image: confluentinc/cp-kafka:7.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: some-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_INTERNAL://127.0.0.1:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1