server:
  port: 8067
spring:
  application:
    name: oath-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
      minimumIdle: 5

eventuate:
  database:
    schema: oath
  eventDispatcherId: localBankCustomerDataHandler
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS}
  zookeeper:
    connection:
      string: zookeeper:2181